Remove claat setup from export action

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -4,12 +4,6 @@ description: |
   Convert Google Docs to codelabs (HTML, Markdown, offline) with CLaat. Includes converting Markdown files to HTML codelabs.
 
 inputs:
-  claat-version:
-    description: |
-      claat version.
-      Default is latest
-    required: false
-    default: "latest"
   command:
     description: |
       claat command. (export, update, serve)
@@ -106,36 +100,12 @@ runs:
         echo "::error title=⛔ error hint::Support Linux Only"
         exit 1
 
-    - name: Export Go bin to all steps
-      id: go-env
+    - name: Check claat command
       shell: bash
       run: |
         echo "::group::Export Go bin to all steps"
-        go version
-        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
-        echo "go-bin-path=$(go env GOPATH)/bin" >> "$GITHUB_OUTPUT"
-        echo "go bin exported."
-        echo "::endgroup::"
-
-    # Save/Restore claat
-    - name: claat cache
-      uses: actions/cache@v4
-      id: claat-cache
-      with:
-        path: |
-          ${{ steps.go-env.outputs.go-bin-path }}/*
-        key: go-claat-${{ inputs.claat-version }}
-
-    - name: Setup claat (latest)
-      if: steps.claat-cache.outputs.cache-hit != 'true'
-      shell: bash
-      env:
-        VERSION: ${{ inputs.claat-version }}
-      run: |
-        echo "::group::Setup claat (latest)"
-        mkdir -p $(go env GOPATH)/bin
-        go install github.com/googlecodelabs/tools/claat@$VERSION
-        claat version
+        claat version >/dev/null 2>&1 || (echo "::error title=⛔ error hint::The command 'claat' is not installed." && exit 1)
+        echo "claat is installed."
         echo "::endgroup::"
 
     - name: Command builder
